apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oj78c0bd7-nodejs
  janus-idp.io/tekton: oj78c0bd7-nodejs
  backstage.io/kubernetes-id: oj78c0bd7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oj78c0bd7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
